# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liszt', '0008_auto_20160218_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='someday',
            field=models.BooleanField(default=False),
        ),
    ]
