# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liszt', '0009_item_someday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='someday',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='list',
            name='tags',
        ),
        migrations.AddField(
            model_name='list',
            name='starred',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
