# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liszt', '0010_auto_20160310_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='for_review',
            field=models.BooleanField(default=False),
        ),
    ]
