# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('liszt', '0011_list_for_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='linked_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_items', to='liszt.List'),
        ),
        migrations.AddField(
            model_name='item',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
